name: react-native-android-build-apk
on:
  push:
    branches:
      - '**'
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease && cd ..
          mv android/app/build/outputs/apk/release/app-release.apk android/app/build/outputs/apk/release/app-${GITHUB_REF##*/}.apk

#       - name: Upload Artifact
#         uses: actions/upload-artifact@v1
#         with:
#           name: app-release.apk
#           path: android/app/build/outputs/apk/release/

      - uses: LanceMcCarthy/Action-AzureBlobUpload@v2
        name: Uploading to Azure storage...
        with:
          connection_string: ${{ secrets.YourAzureBlobConnectionString }}
          container_name: apkstorage
          source_folder: android/app/build/outputs/apk/release/
       
      - uses: act10ns/slack@v1
        name: Slack Notification
        with: 
          status: ${{ job.status }}
          channel: '#general'
          message: Uploaded app-${GITHUB_REF##*/} file Successfully

